### ISSUE TITLE
Create Shiny wireframe

### ISSUE THREAD

**Issue by LukasWallrich** [LukasWallrich/citationProfileR#11]
Example Shiny

[pnas_nudge.zip](https://github.com/LukasWallrich/citationProfileR/files/10874058/pnas_nudge.zip)

**Comment by LukasWallrich** [comment]
Tool that might help with putting the wireframe into code: https://rstudio.github.io/shinyuieditor/

**Comment by abeltranandrade** [comment]
![image](https://user-images.githubusercontent.com/55207237/230438014-775bb668-d5e1-473b-a4eb-69f4d2634c52.png)

**Comment by MackieZhou** [comment]
<img width="913" alt="website_wireframe_04-06" src="https://user-images.githubusercontent.com/55106014/230467484-45d23ca1-54f4-4512-9c62-3de4196d7e00.png">
updated wireframe

**Comment by LukasWallrich** [comment]
> updated wireframe

Looks great! We should do some user testing and see whether the navigation is clear or whether it would benefit from 1 -2 -3 labels or other guidance ... but this is certainly a foundation you can build on.
