### ISSUE TITLE
Crossref - add year to search

### ISSUE THREAD

**Issue by LukasWallrich** [LukasWallrich/citationProfileR#12]
I checked how to use query.bibliographic and just wanted to highlight that you use the github search for that - if you restrict it to R code, you see how other people have done this:

https://github.com/search?l=R&p=2&q=query.bibliographic&type=Code

Everyone using title and year seems to just paste them together - the only attempt to use multiple elements is commented out, so it might not work. An example for combining year and title:

https://github.com/markrobinsonuzh/os_monitor/blob/a6e7e80ac3c14235265ab1daffb72f51c137da49/code/rcrossref_rest.R

**Comment by LukasWallrich** [comment]
@abeltranandrade has this been done? Can't see it in your code, and it seems easy to implement and helpful to increase the crossref accuracy ...

**Comment by abeltranandrade** [comment]
Yes we had written this code. I think due to a merge conflict it accidentally got cut out but I was able to find @lmikhelashvili code on a previous commit and re-add it on [this commit ](https://github.com/LukasWallrich/citationProfileR/commit/bd1b2ce0b139d705f8ddb7afe30316074212209b)
