### ISSUE TITLE
Reconsider use of genderize.io

### ISSUE THREAD

**Issue by LukasWallrich** [LukasWallrich/citationProfileR#20]
I just came across this article that assessed gender-estimation APIs ... and found that genderize.io was by far the weakest: https://pubmed.ncbi.nlm.nih.gov/34629970/

Can you please review and reconsider which we should use? If we have to pay, up to 10 USD per month would be ok for now ...

**Comment by LukasWallrich** [comment]
(The result might well be that the article has issues and that genderize is best ... but we need to be able to respond to that question, and if we need to change direction, we should do that now ...)

**Comment by rithika-d** [comment]
I've changed the code to use the API from https://gender-api.com/ instead and the function works when given any first name. Please let me know if this code as intended.

**Comment by LukasWallrich** [comment]
I think so - except for the comments on Slack. Thanks!
