### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by LukasWallrich** [LukasWallrich/citationProfileR#3]
We should create a logo for the package & app - probably a hexsticker.

The [polaroid](https://jhkim.shinyapps.io/polaroid/) shiny app should work well.

**Comment by lmikhelashvili** [comment]
@LukasWallrich Here is the logo we created. Let me know if you like this and I'll close the issue. 
![CitationProfileR_logo](https://user-images.githubusercontent.com/70569747/234766414-7db2ac6c-5ef8-484f-8fe9-9c48f88773dc.png)

**Comment by LukasWallrich** [comment]
Looks great! Can we please add this to the readme title? Like this:

`# citationProfileR <img src="man/figures/logo.png" align="right" style="height:200px; padding: 10px;" />`

**Comment by lmikhelashvili** [comment]
Added!
