### ISSUE TITLE
Working directory for parse_pdf_refs

### ISSUE THREAD

**Issue by lmikhelashvili** [LukasWallrich/citationProfileR#7]
The working directory set in `parse_pdf_refs` function is a local file path. We have to make the path global. This will create an issue if anyone else tries to run the code. The variable that needs to be changed is `f_bib`.

**Comment by lmikhelashvili** [comment]
@abeltranandrade did we resolve this issue?

**Comment by abeltranandrade** [comment]
Yeah, I don't see f_bib anywhere and there is also no other local paths on the code that could cause it to break.
