### ISSUE TITLE
credit copyrighted code

### ISSUE THREAD

**Issue by MackieZhou** [LukasWallrich/citationProfileR#9]

**Comment by MackieZhou** [comment]
credit copyrighted code taken from other packages, e.g. [GenderGuesser](https://github.com/coccopuffs/GenderGuesser)

**Comment by lmikhelashvili** [comment]
@MackieZhou Did this issue get resolved?

**Comment by MackieZhou** [comment]
In the guess_gender function, there is a comment at the very top of the file with a link to the guessGender package where Rithika & me took/adapted code from. So I think it is resolved.

I don't believe there's any copyrighted code in shiny.

**Comment by LukasWallrich** [comment]
Credit should (also) be given in the DESCRIPTION file (it's not really visible if it's only in the source code) by adding copyright holders in the following format:

    `person("Martin", "Westgate", role = "cph", comment = "Author of included synthesisr fragments")`

This at least needs to be done for GenderGuesser (@MackieZhou) and the list function from the bbr package (@abeltranandrade) - could you please do that?

**Comment by abeltranandrade** [comment]
@rithika-d helped me out and did it!!!!!
